import type { ThemeCollectionItem } from 'vuepress-theme-plume'
import { defineCollection } from 'vuepress-theme-plume'

export const developDoc: ThemeCollectionItem = defineCollection({
  type: 'doc',
  title: '开发文档',
  dir: 'develop',
  linkPrefix: '/develop/',
  sidebar: [
    {
      text: '本地调试',
      collapsed: false,
      icon: 'streamline-ultimate-color:monitor-bug',
      items: [
        '',
        'installenv',
        'getcode',
        'codefiletree',
        'dev',
      ],
    },
    {
      text: '后端',
      prefix: 'backend',
      icon: 'streamline-cyber-color:server',
      collapsed: false,
      items: [
        '',
        'database',
        'globalvariable',
        {
          text: '系统超级管理员',
          icon: 'grommet-icons:user-admin',
          collapsed: true,
          prefix: 'spueradmin',
          // items: ['','测试', 'collection-doc'],
          items: 'auto',
        },
        {
          text: '系统管理员',
          icon: 'grommet-icons:user-admin',
          collapsed: true,
          prefix: 'admin',
          items: 'auto',
          // items: ['','collection-post', 'collection-doc'],
        },
        {
          text: '团队管理员',
          icon: 'grommet-icons:user-admin',
          collapsed: true,
          prefix: 'teamadmin',
          items: 'auto',
          // items: ['','collection-post', 'collection-doc'],
        }, 
        {
          text: '团队成员',
          icon: 'grommet-icons:user-admin',
          collapsed: true,
          prefix: 'teammember',
          items: 'auto',
          // items: ['','collection-post', 'collection-doc'],
        },
        {
          text: '普通用户',
          icon: 'grommet-icons:user-admin',
          collapsed: true,
          prefix: 'user',
          items: 'auto',
          // items: ['','collection-post', 'collection-doc'],
        },
        'globalmiddleware',
      ],
    },
    {
      text: '前端',
      prefix: 'frontend',
      icon: 'fa6-solid:computer',
      collapsed: false,
      items: 'auto',
      // items: [
      //   '',
      //   'shiki',
      //   'search',
      //   'reading-time',
      //   'llms',
      //   'markdown-enhance',
      //   'markdown-power',
      //   'markdown-image',
      //   'markdown-math',
      //   'markdown-include',
      //   'watermark',
      // ],
    },
  ],
})
